[package]
name = "cpudetect"
version = "0.0.1"
edition = "2024"

[lib]
name = "cpudetect"
path = "src/lib.rs"
crate-type = ["rlib", "dylib", "staticlib"]

[[bin]]
name = "lscpu"
path = "bin/lscpu.rs"
required-features = ["std"]

[features]
default = ["std"]
std = ["alloc", "bitflags/std", "dep:colored"]
alloc = []

[dependencies]
bitflags = { version = "2.10.0", default-features = false }
colored = { version = "3.0.0", optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
